version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - ./vol/app/gen-kapp-server:/home/node/app
      - "/etc/localtime:/etc/localtime"
    ports:
     - "8081:3000"
    command: " npm run dev"