version: "2"
services:
  minio1:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    volumes:
     - ../vol/data1:/data
    ports:
     - "9005:9000"
    environment:
     MINIO_ACCESS_KEY: minio123
     MINIO_SECRET_KEY: minio123
    command: server /data